name: chip_list
description: Makes creating a list of ChoiceChip-s a breeze. Super customizable as well.
version: 3.1.0
homepage: https://github.com/bossbeagle1509/chip_list

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
